title: "Quad Sim"
remote_theme: pmarsceill/just-the-docs
color_scheme: "light"
search_enabled: true

# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "Quad Sim on GitHub":
    - "//github.com/rumaisaabdulhai/quad_sim"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"